import { type Container } from "./Container";
import type { EventName, Callback, Rect } from "./type";
import { Matrix } from "./utils/Matrix";
import type TinyUI from "./TinyUI";
export declare class DisplayObject {
    app: TinyUI;
    parent: Container | null;
    isScaleAffectedSize: boolean;
    x: number;
    y: number;
    width: number;
    height: number;
    visible: boolean;
    scaleX: number;
    scaleY: number;
    anchorX: number;
    anchorY: number;
    alpha: number;
    name: string;
    rotation: number;
    private eventListeners;
    constructor(app: TinyUI, name?: string);
    addEventListener(eventName: EventName, handler: Callback): void;
    removeEventListener(eventName: EventName, handler: Callback): void;
    dispatchEvent(eventName: EventName, event: any): void;
    hasEventListener(eventName: EventName): boolean;
    getLocalTransformMatrix(): Matrix;
    getGlobalTransformMatrix(): Matrix;
    getBounds(): Rect;
    hitTest(x: number, y: number): boolean;
    render(_matrix: Matrix): void;
    destroy(): void;
}
