import { DisplayObject } from "./DisplayObject";
import type TinyUI from "./TinyUI";
import { type Matrix } from "./utils/Matrix";
type FontWeight = 'normal' | 'bold';
type TextAlign = 'left' | 'center' | 'right';
export declare class Text extends DisplayObject {
    private _text;
    private _color;
    private _fontFamily;
    private _fontSize;
    private _lineHeight;
    private _fontWeight;
    private _maxWidth;
    private _align;
    texture: WebGLTexture | null;
    textureNeedsUpdate: boolean;
    private previousText;
    constructor(app: TinyUI, name?: string);
    get text(): string;
    get color(): string;
    get fontFamily(): string;
    get fontSize(): number;
    get lineHeight(): number;
    get fontWeight(): FontWeight;
    get maxWidth(): number;
    get align(): TextAlign;
    set text(text: string);
    set color(color: string);
    set fontFamily(fontFamily: string);
    set fontSize(fontSize: number);
    set lineHeight(lineHeight: number);
    set fontWeight(fontWeight: FontWeight);
    set maxWidth(maxWidth: number);
    set align(align: TextAlign);
    updateTexture(): void;
    destroy(): void;
    render(_matrix: Matrix): void;
}
export {};
