import { Bitmap } from "./Bitmap";
import { Text } from "./Text";
import { Container } from "./Container";
import { DisplayObject } from "./DisplayObject";
import { Graphics } from "./Graphics";
import { Color } from "./type";
import { EventManager } from "./utils/EventManager";
import { Matrix } from "./utils/Matrix";
import { ShaderManager } from "./utils/ShaderManager";
import { TextureManager } from "./utils/TextureManager";
declare class TinyUI {
    canvas: HTMLCanvasElement;
    gl: WebGLRenderingContext;
    shaderManager: ShaderManager;
    textureManager: TextureManager;
    eventManager: EventManager;
    private shaderProgram;
    private positionLocation;
    private texCoordLocation;
    private colorLocation;
    private matrixLocation;
    private resolutionLocation;
    _imageLocation: WebGLUniformLocation | null;
    _useTextureLocation: WebGLUniformLocation | null;
    private positionBuffer;
    private texCoordBuffer;
    private colorBuffer;
    private indexBuffer;
    private viewportWidth;
    private viewportHeight;
    private currentMatrix;
    root: Container;
    constructor(canvas: HTMLCanvasElement, options?: WebGLContextAttributes);
    private updateViewport;
    private initShaders;
    private initBuffers;
    render(): void;
    patchRender(): void;
    _renderTree(node: DisplayObject, parentMatrix?: Matrix, parentAlpha?: number): void;
    _setBufferData(positions: number[], texCoords: number[], colors: number[], indices: number[]): void;
    parseColor(color: string): Color;
    loadTexture(url: string): Promise<WebGLTexture>;
    resetGLState(): void;
    destroy(): void;
    createBitmapFromUrl(url: string): Promise<Bitmap>;
    createBitmapFromImage(image: HTMLImageElement): Bitmap;
    createText(textContent: string): Text;
    createContainer(name?: string): Container;
    createGraphics(name?: string): Graphics;
    testRender(x: number, y: number, width: number, height: number): void;
}
export = TinyUI;
